use sdl2::keyboard::Keycode as Sdl2Keycode;

use super::scancode::Scancode;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serializing", derive(serde::Serialize, serde::Deserialize))]
pub enum Keycode {
	Backspace,
	Tab,
	Return,
	Escape,
	Space,
	Exclaim,
	Quotedbl,
	Hash,
	Dollar,
	Percent,
	Ampersand,
	Quote,
	LeftParen,
	RightParen,
	Asterisk,
	Plus,
	Comma,
	Minus,
	Period,
	Slash,
	Num0,
	Num1,
	Num2,
	Num3,
	Num4,
	Num5,
	Num6,
	Num7,
	Num8,
	Num9,
	Colon,
	Semicolon,
	Less,
	Equals,
	Greater,
	Question,
	At,
	LeftBracket,
	Backslash,
	RightBracket,
	Caret,
	Underscore,
	Backquote,
	A,
	B,
	C,
	D,
	E,
	F,
	G,
	H,
	I,
	J,
	K,
	L,
	M,
	N,
	O,
	P,
	Q,
	R,
	S,
	T,
	U,
	V,
	W,
	X,
	Y,
	Z,
	Delete,
	CapsLock,
	F1,
	F2,
	F3,
	F4,
	F5,
	F6,
	F7,
	F8,
	F9,
	F10,
	F11,
	F12,
	PrintScreen,
	ScrollLock,
	Pause,
	Insert,
	Home,
	PageUp,
	End,
	PageDown,
	Right,
	Left,
	Down,
	Up,
	NumLockClear,
	KpDivide,
	KpMultiply,
	KpMinus,
	KpPlus,
	KpEnter,
	Kp1,
	Kp2,
	Kp3,
	Kp4,
	Kp5,
	Kp6,
	Kp7,
	Kp8,
	Kp9,
	Kp0,
	KpPeriod,
	Application,
	Power,
	KpEquals,
	F13,
	F14,
	F15,
	F16,
	F17,
	F18,
	F19,
	F20,
	F21,
	F22,
	F23,
	F24,
	Execute,
	Help,
	Menu,
	Select,
	Stop,
	Again,
	Undo,
	Cut,
	Copy,
	Paste,
	Find,
	Mute,
	VolumeUp,
	VolumeDown,
	KpComma,
	KpEqualsAS400,
	AltErase,
	Sysreq,
	Cancel,
	Clear,
	Prior,
	Return2,
	Separator,
	Out,
	Oper,
	ClearAgain,
	CrSel,
	ExSel,
	Kp00,
	Kp000,
	ThousandsSeparator,
	DecimalSeparator,
	CurrencyUnit,
	CurrencySubUnit,
	KpLeftParen,
	KpRightParen,
	KpLeftBrace,
	KpRightBrace,
	KpTab,
	KpBackspace,
	KpA,
	KpB,
	KpC,
	KpD,
	KpE,
	KpF,
	KpXor,
	KpPower,
	KpPercent,
	KpLess,
	KpGreater,
	KpAmpersand,
	KpDblAmpersand,
	KpVerticalBar,
	KpDblVerticalBar,
	KpColon,
	KpHash,
	KpSpace,
	KpAt,
	KpExclam,
	KpMemStore,
	KpMemRecall,
	KpMemClear,
	KpMemAdd,
	KpMemSubtract,
	KpMemMultiply,
	KpMemDivide,
	KpPlusMinus,
	KpClear,
	KpClearEntry,
	KpBinary,
	KpOctal,
	KpDecimal,
	KpHexadecimal,
	LCtrl,
	LShift,
	LAlt,
	LGui,
	RCtrl,
	RShift,
	RAlt,
	RGui,
	Mode,
	AudioNext,
	AudioPrev,
	AudioStop,
	AudioPlay,
	AudioMute,
	MediaSelect,
	Www,
	Mail,
	Calculator,
	Computer,
	AcSearch,
	AcHome,
	AcBack,
	AcForward,
	AcStop,
	AcRefresh,
	AcBookmarks,
	BrightnessDown,
	BrightnessUp,
	DisplaySwitch,
	KbdIllumToggle,
	KbdIllumDown,
	KbdIllumUp,
	Eject,
	Sleep,
}

impl From<Sdl2Keycode> for Keycode {
	fn from(value: Sdl2Keycode) -> Self {
		match value {
			Sdl2Keycode::Backspace => Keycode::Backspace,
			Sdl2Keycode::Tab => Keycode::Tab,
			Sdl2Keycode::Return => Keycode::Return,
			Sdl2Keycode::Escape => Keycode::Escape,
			Sdl2Keycode::Space => Keycode::Space,
			Sdl2Keycode::Exclaim => Keycode::Exclaim,
			Sdl2Keycode::Quotedbl => Keycode::Quotedbl,
			Sdl2Keycode::Hash => Keycode::Hash,
			Sdl2Keycode::Dollar => Keycode::Dollar,
			Sdl2Keycode::Percent => Keycode::Percent,
			Sdl2Keycode::Ampersand => Keycode::Ampersand,
			Sdl2Keycode::Quote => Keycode::Quote,
			Sdl2Keycode::LeftParen => Keycode::LeftParen,
			Sdl2Keycode::RightParen => Keycode::RightParen,
			Sdl2Keycode::Asterisk => Keycode::Asterisk,
			Sdl2Keycode::Plus => Keycode::Plus,
			Sdl2Keycode::Comma => Keycode::Comma,
			Sdl2Keycode::Minus => Keycode::Minus,
			Sdl2Keycode::Period => Keycode::Period,
			Sdl2Keycode::Slash => Keycode::Slash,
			Sdl2Keycode::Num0 => Keycode::Num0,
			Sdl2Keycode::Num1 => Keycode::Num1,
			Sdl2Keycode::Num2 => Keycode::Num2,
			Sdl2Keycode::Num3 => Keycode::Num3,
			Sdl2Keycode::Num4 => Keycode::Num4,
			Sdl2Keycode::Num5 => Keycode::Num5,
			Sdl2Keycode::Num6 => Keycode::Num6,
			Sdl2Keycode::Num7 => Keycode::Num7,
			Sdl2Keycode::Num8 => Keycode::Num8,
			Sdl2Keycode::Num9 => Keycode::Num9,
			Sdl2Keycode::Colon => Keycode::Colon,
			Sdl2Keycode::Semicolon => Keycode::Semicolon,
			Sdl2Keycode::Less => Keycode::Less,
			Sdl2Keycode::Equals => Keycode::Equals,
			Sdl2Keycode::Greater => Keycode::Greater,
			Sdl2Keycode::Question => Keycode::Question,
			Sdl2Keycode::At => Keycode::At,
			Sdl2Keycode::LeftBracket => Keycode::LeftBracket,
			Sdl2Keycode::Backslash => Keycode::Backslash,
			Sdl2Keycode::RightBracket => Keycode::RightBracket,
			Sdl2Keycode::Caret => Keycode::Caret,
			Sdl2Keycode::Underscore => Keycode::Underscore,
			Sdl2Keycode::Backquote => Keycode::Backquote,
			Sdl2Keycode::A => Keycode::A,
			Sdl2Keycode::B => Keycode::B,
			Sdl2Keycode::C => Keycode::C,
			Sdl2Keycode::D => Keycode::D,
			Sdl2Keycode::E => Keycode::E,
			Sdl2Keycode::F => Keycode::F,
			Sdl2Keycode::G => Keycode::G,
			Sdl2Keycode::H => Keycode::H,
			Sdl2Keycode::I => Keycode::I,
			Sdl2Keycode::J => Keycode::J,
			Sdl2Keycode::K => Keycode::K,
			Sdl2Keycode::L => Keycode::L,
			Sdl2Keycode::M => Keycode::M,
			Sdl2Keycode::N => Keycode::N,
			Sdl2Keycode::O => Keycode::O,
			Sdl2Keycode::P => Keycode::P,
			Sdl2Keycode::Q => Keycode::Q,
			Sdl2Keycode::R => Keycode::R,
			Sdl2Keycode::S => Keycode::S,
			Sdl2Keycode::T => Keycode::T,
			Sdl2Keycode::U => Keycode::U,
			Sdl2Keycode::V => Keycode::V,
			Sdl2Keycode::W => Keycode::W,
			Sdl2Keycode::X => Keycode::X,
			Sdl2Keycode::Y => Keycode::Y,
			Sdl2Keycode::Z => Keycode::Z,
			Sdl2Keycode::Delete => Keycode::Delete,
			Sdl2Keycode::CapsLock => Keycode::CapsLock,
			Sdl2Keycode::F1 => Keycode::F1,
			Sdl2Keycode::F2 => Keycode::F2,
			Sdl2Keycode::F3 => Keycode::F3,
			Sdl2Keycode::F4 => Keycode::F4,
			Sdl2Keycode::F5 => Keycode::F5,
			Sdl2Keycode::F6 => Keycode::F6,
			Sdl2Keycode::F7 => Keycode::F7,
			Sdl2Keycode::F8 => Keycode::F8,
			Sdl2Keycode::F9 => Keycode::F9,
			Sdl2Keycode::F10 => Keycode::F10,
			Sdl2Keycode::F11 => Keycode::F11,
			Sdl2Keycode::F12 => Keycode::F12,
			Sdl2Keycode::PrintScreen => Keycode::PrintScreen,
			Sdl2Keycode::ScrollLock => Keycode::ScrollLock,
			Sdl2Keycode::Pause => Keycode::Pause,
			Sdl2Keycode::Insert => Keycode::Insert,
			Sdl2Keycode::Home => Keycode::Home,
			Sdl2Keycode::PageUp => Keycode::PageUp,
			Sdl2Keycode::End => Keycode::End,
			Sdl2Keycode::PageDown => Keycode::PageDown,
			Sdl2Keycode::Right => Keycode::Right,
			Sdl2Keycode::Left => Keycode::Left,
			Sdl2Keycode::Down => Keycode::Down,
			Sdl2Keycode::Up => Keycode::Up,
			Sdl2Keycode::NumLockClear => Keycode::NumLockClear,
			Sdl2Keycode::KpDivide => Keycode::KpDivide,
			Sdl2Keycode::KpMultiply => Keycode::KpMultiply,
			Sdl2Keycode::KpMinus => Keycode::KpMinus,
			Sdl2Keycode::KpPlus => Keycode::KpPlus,
			Sdl2Keycode::KpEnter => Keycode::KpEnter,
			Sdl2Keycode::Kp1 => Keycode::Kp1,
			Sdl2Keycode::Kp2 => Keycode::Kp2,
			Sdl2Keycode::Kp3 => Keycode::Kp3,
			Sdl2Keycode::Kp4 => Keycode::Kp4,
			Sdl2Keycode::Kp5 => Keycode::Kp5,
			Sdl2Keycode::Kp6 => Keycode::Kp6,
			Sdl2Keycode::Kp7 => Keycode::Kp7,
			Sdl2Keycode::Kp8 => Keycode::Kp8,
			Sdl2Keycode::Kp9 => Keycode::Kp9,
			Sdl2Keycode::Kp0 => Keycode::Kp0,
			Sdl2Keycode::KpPeriod => Keycode::KpPeriod,
			Sdl2Keycode::Application => Keycode::Application,
			Sdl2Keycode::Power => Keycode::Power,
			Sdl2Keycode::KpEquals => Keycode::KpEquals,
			Sdl2Keycode::F13 => Keycode::F13,
			Sdl2Keycode::F14 => Keycode::F14,
			Sdl2Keycode::F15 => Keycode::F15,
			Sdl2Keycode::F16 => Keycode::F16,
			Sdl2Keycode::F17 => Keycode::F17,
			Sdl2Keycode::F18 => Keycode::F18,
			Sdl2Keycode::F19 => Keycode::F19,
			Sdl2Keycode::F20 => Keycode::F20,
			Sdl2Keycode::F21 => Keycode::F21,
			Sdl2Keycode::F22 => Keycode::F22,
			Sdl2Keycode::F23 => Keycode::F23,
			Sdl2Keycode::F24 => Keycode::F24,
			Sdl2Keycode::Execute => Keycode::Execute,
			Sdl2Keycode::Help => Keycode::Help,
			Sdl2Keycode::Menu => Keycode::Menu,
			Sdl2Keycode::Select => Keycode::Select,
			Sdl2Keycode::Stop => Keycode::Stop,
			Sdl2Keycode::Again => Keycode::Again,
			Sdl2Keycode::Undo => Keycode::Undo,
			Sdl2Keycode::Cut => Keycode::Cut,
			Sdl2Keycode::Copy => Keycode::Copy,
			Sdl2Keycode::Paste => Keycode::Paste,
			Sdl2Keycode::Find => Keycode::Find,
			Sdl2Keycode::Mute => Keycode::Mute,
			Sdl2Keycode::VolumeUp => Keycode::VolumeUp,
			Sdl2Keycode::VolumeDown => Keycode::VolumeDown,
			Sdl2Keycode::KpComma => Keycode::KpComma,
			Sdl2Keycode::KpEqualsAS400 => Keycode::KpEqualsAS400,
			Sdl2Keycode::AltErase => Keycode::AltErase,
			Sdl2Keycode::Sysreq => Keycode::Sysreq,
			Sdl2Keycode::Cancel => Keycode::Cancel,
			Sdl2Keycode::Clear => Keycode::Clear,
			Sdl2Keycode::Prior => Keycode::Prior,
			Sdl2Keycode::Return2 => Keycode::Return2,
			Sdl2Keycode::Separator => Keycode::Separator,
			Sdl2Keycode::Out => Keycode::Out,
			Sdl2Keycode::Oper => Keycode::Oper,
			Sdl2Keycode::ClearAgain => Keycode::ClearAgain,
			Sdl2Keycode::CrSel => Keycode::CrSel,
			Sdl2Keycode::ExSel => Keycode::ExSel,
			Sdl2Keycode::Kp00 => Keycode::Kp00,
			Sdl2Keycode::Kp000 => Keycode::Kp000,
			Sdl2Keycode::ThousandsSeparator => Keycode::ThousandsSeparator,
			Sdl2Keycode::DecimalSeparator => Keycode::DecimalSeparator,
			Sdl2Keycode::CurrencyUnit => Keycode::CurrencyUnit,
			Sdl2Keycode::CurrencySubUnit => Keycode::CurrencySubUnit,
			Sdl2Keycode::KpLeftParen => Keycode::KpLeftParen,
			Sdl2Keycode::KpRightParen => Keycode::KpRightParen,
			Sdl2Keycode::KpLeftBrace => Keycode::KpLeftBrace,
			Sdl2Keycode::KpRightBrace => Keycode::KpRightBrace,
			Sdl2Keycode::KpTab => Keycode::KpTab,
			Sdl2Keycode::KpBackspace => Keycode::KpBackspace,
			Sdl2Keycode::KpA => Keycode::KpA,
			Sdl2Keycode::KpB => Keycode::KpB,
			Sdl2Keycode::KpC => Keycode::KpC,
			Sdl2Keycode::KpD => Keycode::KpD,
			Sdl2Keycode::KpE => Keycode::KpE,
			Sdl2Keycode::KpF => Keycode::KpF,
			Sdl2Keycode::KpXor => Keycode::KpXor,
			Sdl2Keycode::KpPower => Keycode::KpPower,
			Sdl2Keycode::KpPercent => Keycode::KpPercent,
			Sdl2Keycode::KpLess => Keycode::KpLess,
			Sdl2Keycode::KpGreater => Keycode::KpGreater,
			Sdl2Keycode::KpAmpersand => Keycode::KpAmpersand,
			Sdl2Keycode::KpDblAmpersand => Keycode::KpDblAmpersand,
			Sdl2Keycode::KpVerticalBar => Keycode::KpVerticalBar,
			Sdl2Keycode::KpDblVerticalBar => Keycode::KpDblVerticalBar,
			Sdl2Keycode::KpColon => Keycode::KpColon,
			Sdl2Keycode::KpHash => Keycode::KpHash,
			Sdl2Keycode::KpSpace => Keycode::KpSpace,
			Sdl2Keycode::KpAt => Keycode::KpAt,
			Sdl2Keycode::KpExclam => Keycode::KpExclam,
			Sdl2Keycode::KpMemStore => Keycode::KpMemStore,
			Sdl2Keycode::KpMemRecall => Keycode::KpMemRecall,
			Sdl2Keycode::KpMemClear => Keycode::KpMemClear,
			Sdl2Keycode::KpMemAdd => Keycode::KpMemAdd,
			Sdl2Keycode::KpMemSubtract => Keycode::KpMemSubtract,
			Sdl2Keycode::KpMemMultiply => Keycode::KpMemMultiply,
			Sdl2Keycode::KpMemDivide => Keycode::KpMemDivide,
			Sdl2Keycode::KpPlusMinus => Keycode::KpPlusMinus,
			Sdl2Keycode::KpClear => Keycode::KpClear,
			Sdl2Keycode::KpClearEntry => Keycode::KpClearEntry,
			Sdl2Keycode::KpBinary => Keycode::KpBinary,
			Sdl2Keycode::KpOctal => Keycode::KpOctal,
			Sdl2Keycode::KpDecimal => Keycode::KpDecimal,
			Sdl2Keycode::KpHexadecimal => Keycode::KpHexadecimal,
			Sdl2Keycode::LCtrl => Keycode::LCtrl,
			Sdl2Keycode::LShift => Keycode::LShift,
			Sdl2Keycode::LAlt => Keycode::LAlt,
			Sdl2Keycode::LGui => Keycode::LGui,
			Sdl2Keycode::RCtrl => Keycode::RCtrl,
			Sdl2Keycode::RShift => Keycode::RShift,
			Sdl2Keycode::RAlt => Keycode::RAlt,
			Sdl2Keycode::RGui => Keycode::RGui,
			Sdl2Keycode::Mode => Keycode::Mode,
			Sdl2Keycode::AudioNext => Keycode::AudioNext,
			Sdl2Keycode::AudioPrev => Keycode::AudioPrev,
			Sdl2Keycode::AudioStop => Keycode::AudioStop,
			Sdl2Keycode::AudioPlay => Keycode::AudioPlay,
			Sdl2Keycode::AudioMute => Keycode::AudioMute,
			Sdl2Keycode::MediaSelect => Keycode::MediaSelect,
			Sdl2Keycode::Www => Keycode::Www,
			Sdl2Keycode::Mail => Keycode::Mail,
			Sdl2Keycode::Calculator => Keycode::Calculator,
			Sdl2Keycode::Computer => Keycode::Computer,
			Sdl2Keycode::AcSearch => Keycode::AcSearch,
			Sdl2Keycode::AcHome => Keycode::AcHome,
			Sdl2Keycode::AcBack => Keycode::AcBack,
			Sdl2Keycode::AcForward => Keycode::AcForward,
			Sdl2Keycode::AcStop => Keycode::AcStop,
			Sdl2Keycode::AcRefresh => Keycode::AcRefresh,
			Sdl2Keycode::AcBookmarks => Keycode::AcBookmarks,
			Sdl2Keycode::BrightnessDown => Keycode::BrightnessDown,
			Sdl2Keycode::BrightnessUp => Keycode::BrightnessUp,
			Sdl2Keycode::DisplaySwitch => Keycode::DisplaySwitch,
			Sdl2Keycode::KbdIllumToggle => Keycode::KbdIllumToggle,
			Sdl2Keycode::KbdIllumDown => Keycode::KbdIllumDown,
			Sdl2Keycode::KbdIllumUp => Keycode::KbdIllumUp,
			Sdl2Keycode::Eject => Keycode::Eject,
			Sdl2Keycode::Sleep => Keycode::Sleep,
		}
	}
}

impl From<Keycode> for Sdl2Keycode {
	fn from(value: Keycode) -> Self {
		match value {
			Keycode::Backspace => Sdl2Keycode::Backspace,
			Keycode::Tab => Sdl2Keycode::Tab,
			Keycode::Return => Sdl2Keycode::Return,
			Keycode::Escape => Sdl2Keycode::Escape,
			Keycode::Space => Sdl2Keycode::Space,
			Keycode::Exclaim => Sdl2Keycode::Exclaim,
			Keycode::Quotedbl => Sdl2Keycode::Quotedbl,
			Keycode::Hash => Sdl2Keycode::Hash,
			Keycode::Dollar => Sdl2Keycode::Dollar,
			Keycode::Percent => Sdl2Keycode::Percent,
			Keycode::Ampersand => Sdl2Keycode::Ampersand,
			Keycode::Quote => Sdl2Keycode::Quote,
			Keycode::LeftParen => Sdl2Keycode::LeftParen,
			Keycode::RightParen => Sdl2Keycode::RightParen,
			Keycode::Asterisk => Sdl2Keycode::Asterisk,
			Keycode::Plus => Sdl2Keycode::Plus,
			Keycode::Comma => Sdl2Keycode::Comma,
			Keycode::Minus => Sdl2Keycode::Minus,
			Keycode::Period => Sdl2Keycode::Period,
			Keycode::Slash => Sdl2Keycode::Slash,
			Keycode::Num0 => Sdl2Keycode::Num0,
			Keycode::Num1 => Sdl2Keycode::Num1,
			Keycode::Num2 => Sdl2Keycode::Num2,
			Keycode::Num3 => Sdl2Keycode::Num3,
			Keycode::Num4 => Sdl2Keycode::Num4,
			Keycode::Num5 => Sdl2Keycode::Num5,
			Keycode::Num6 => Sdl2Keycode::Num6,
			Keycode::Num7 => Sdl2Keycode::Num7,
			Keycode::Num8 => Sdl2Keycode::Num8,
			Keycode::Num9 => Sdl2Keycode::Num9,
			Keycode::Colon => Sdl2Keycode::Colon,
			Keycode::Semicolon => Sdl2Keycode::Semicolon,
			Keycode::Less => Sdl2Keycode::Less,
			Keycode::Equals => Sdl2Keycode::Equals,
			Keycode::Greater => Sdl2Keycode::Greater,
			Keycode::Question => Sdl2Keycode::Question,
			Keycode::At => Sdl2Keycode::At,
			Keycode::LeftBracket => Sdl2Keycode::LeftBracket,
			Keycode::Backslash => Sdl2Keycode::Backslash,
			Keycode::RightBracket => Sdl2Keycode::RightBracket,
			Keycode::Caret => Sdl2Keycode::Caret,
			Keycode::Underscore => Sdl2Keycode::Underscore,
			Keycode::Backquote => Sdl2Keycode::Backquote,
			Keycode::A => Sdl2Keycode::A,
			Keycode::B => Sdl2Keycode::B,
			Keycode::C => Sdl2Keycode::C,
			Keycode::D => Sdl2Keycode::D,
			Keycode::E => Sdl2Keycode::E,
			Keycode::F => Sdl2Keycode::F,
			Keycode::G => Sdl2Keycode::G,
			Keycode::H => Sdl2Keycode::H,
			Keycode::I => Sdl2Keycode::I,
			Keycode::J => Sdl2Keycode::J,
			Keycode::K => Sdl2Keycode::K,
			Keycode::L => Sdl2Keycode::L,
			Keycode::M => Sdl2Keycode::M,
			Keycode::N => Sdl2Keycode::N,
			Keycode::O => Sdl2Keycode::O,
			Keycode::P => Sdl2Keycode::P,
			Keycode::Q => Sdl2Keycode::Q,
			Keycode::R => Sdl2Keycode::R,
			Keycode::S => Sdl2Keycode::S,
			Keycode::T => Sdl2Keycode::T,
			Keycode::U => Sdl2Keycode::U,
			Keycode::V => Sdl2Keycode::V,
			Keycode::W => Sdl2Keycode::W,
			Keycode::X => Sdl2Keycode::X,
			Keycode::Y => Sdl2Keycode::Y,
			Keycode::Z => Sdl2Keycode::Z,
			Keycode::Delete => Sdl2Keycode::Delete,
			Keycode::CapsLock => Sdl2Keycode::CapsLock,
			Keycode::F1 => Sdl2Keycode::F1,
			Keycode::F2 => Sdl2Keycode::F2,
			Keycode::F3 => Sdl2Keycode::F3,
			Keycode::F4 => Sdl2Keycode::F4,
			Keycode::F5 => Sdl2Keycode::F5,
			Keycode::F6 => Sdl2Keycode::F6,
			Keycode::F7 => Sdl2Keycode::F7,
			Keycode::F8 => Sdl2Keycode::F8,
			Keycode::F9 => Sdl2Keycode::F9,
			Keycode::F10 => Sdl2Keycode::F10,
			Keycode::F11 => Sdl2Keycode::F11,
			Keycode::F12 => Sdl2Keycode::F12,
			Keycode::PrintScreen => Sdl2Keycode::PrintScreen,
			Keycode::ScrollLock => Sdl2Keycode::ScrollLock,
			Keycode::Pause => Sdl2Keycode::Pause,
			Keycode::Insert => Sdl2Keycode::Insert,
			Keycode::Home => Sdl2Keycode::Home,
			Keycode::PageUp => Sdl2Keycode::PageUp,
			Keycode::End => Sdl2Keycode::End,
			Keycode::PageDown => Sdl2Keycode::PageDown,
			Keycode::Right => Sdl2Keycode::Right,
			Keycode::Left => Sdl2Keycode::Left,
			Keycode::Down => Sdl2Keycode::Down,
			Keycode::Up => Sdl2Keycode::Up,
			Keycode::NumLockClear => Sdl2Keycode::NumLockClear,
			Keycode::KpDivide => Sdl2Keycode::KpDivide,
			Keycode::KpMultiply => Sdl2Keycode::KpMultiply,
			Keycode::KpMinus => Sdl2Keycode::KpMinus,
			Keycode::KpPlus => Sdl2Keycode::KpPlus,
			Keycode::KpEnter => Sdl2Keycode::KpEnter,
			Keycode::Kp1 => Sdl2Keycode::Kp1,
			Keycode::Kp2 => Sdl2Keycode::Kp2,
			Keycode::Kp3 => Sdl2Keycode::Kp3,
			Keycode::Kp4 => Sdl2Keycode::Kp4,
			Keycode::Kp5 => Sdl2Keycode::Kp5,
			Keycode::Kp6 => Sdl2Keycode::Kp6,
			Keycode::Kp7 => Sdl2Keycode::Kp7,
			Keycode::Kp8 => Sdl2Keycode::Kp8,
			Keycode::Kp9 => Sdl2Keycode::Kp9,
			Keycode::Kp0 => Sdl2Keycode::Kp0,
			Keycode::KpPeriod => Sdl2Keycode::KpPeriod,
			Keycode::Application => Sdl2Keycode::Application,
			Keycode::Power => Sdl2Keycode::Power,
			Keycode::KpEquals => Sdl2Keycode::KpEquals,
			Keycode::F13 => Sdl2Keycode::F13,
			Keycode::F14 => Sdl2Keycode::F14,
			Keycode::F15 => Sdl2Keycode::F15,
			Keycode::F16 => Sdl2Keycode::F16,
			Keycode::F17 => Sdl2Keycode::F17,
			Keycode::F18 => Sdl2Keycode::F18,
			Keycode::F19 => Sdl2Keycode::F19,
			Keycode::F20 => Sdl2Keycode::F20,
			Keycode::F21 => Sdl2Keycode::F21,
			Keycode::F22 => Sdl2Keycode::F22,
			Keycode::F23 => Sdl2Keycode::F23,
			Keycode::F24 => Sdl2Keycode::F24,
			Keycode::Execute => Sdl2Keycode::Execute,
			Keycode::Help => Sdl2Keycode::Help,
			Keycode::Menu => Sdl2Keycode::Menu,
			Keycode::Select => Sdl2Keycode::Select,
			Keycode::Stop => Sdl2Keycode::Stop,
			Keycode::Again => Sdl2Keycode::Again,
			Keycode::Undo => Sdl2Keycode::Undo,
			Keycode::Cut => Sdl2Keycode::Cut,
			Keycode::Copy => Sdl2Keycode::Copy,
			Keycode::Paste => Sdl2Keycode::Paste,
			Keycode::Find => Sdl2Keycode::Find,
			Keycode::Mute => Sdl2Keycode::Mute,
			Keycode::VolumeUp => Sdl2Keycode::VolumeUp,
			Keycode::VolumeDown => Sdl2Keycode::VolumeDown,
			Keycode::KpComma => Sdl2Keycode::KpComma,
			Keycode::KpEqualsAS400 => Sdl2Keycode::KpEqualsAS400,
			Keycode::AltErase => Sdl2Keycode::AltErase,
			Keycode::Sysreq => Sdl2Keycode::Sysreq,
			Keycode::Cancel => Sdl2Keycode::Cancel,
			Keycode::Clear => Sdl2Keycode::Clear,
			Keycode::Prior => Sdl2Keycode::Prior,
			Keycode::Return2 => Sdl2Keycode::Return2,
			Keycode::Separator => Sdl2Keycode::Separator,
			Keycode::Out => Sdl2Keycode::Out,
			Keycode::Oper => Sdl2Keycode::Oper,
			Keycode::ClearAgain => Sdl2Keycode::ClearAgain,
			Keycode::CrSel => Sdl2Keycode::CrSel,
			Keycode::ExSel => Sdl2Keycode::ExSel,
			Keycode::Kp00 => Sdl2Keycode::Kp00,
			Keycode::Kp000 => Sdl2Keycode::Kp000,
			Keycode::ThousandsSeparator => Sdl2Keycode::ThousandsSeparator,
			Keycode::DecimalSeparator => Sdl2Keycode::DecimalSeparator,
			Keycode::CurrencyUnit => Sdl2Keycode::CurrencyUnit,
			Keycode::CurrencySubUnit => Sdl2Keycode::CurrencySubUnit,
			Keycode::KpLeftParen => Sdl2Keycode::KpLeftParen,
			Keycode::KpRightParen => Sdl2Keycode::KpRightParen,
			Keycode::KpLeftBrace => Sdl2Keycode::KpLeftBrace,
			Keycode::KpRightBrace => Sdl2Keycode::KpRightBrace,
			Keycode::KpTab => Sdl2Keycode::KpTab,
			Keycode::KpBackspace => Sdl2Keycode::KpBackspace,
			Keycode::KpA => Sdl2Keycode::KpA,
			Keycode::KpB => Sdl2Keycode::KpB,
			Keycode::KpC => Sdl2Keycode::KpC,
			Keycode::KpD => Sdl2Keycode::KpD,
			Keycode::KpE => Sdl2Keycode::KpE,
			Keycode::KpF => Sdl2Keycode::KpF,
			Keycode::KpXor => Sdl2Keycode::KpXor,
			Keycode::KpPower => Sdl2Keycode::KpPower,
			Keycode::KpPercent => Sdl2Keycode::KpPercent,
			Keycode::KpLess => Sdl2Keycode::KpLess,
			Keycode::KpGreater => Sdl2Keycode::KpGreater,
			Keycode::KpAmpersand => Sdl2Keycode::KpAmpersand,
			Keycode::KpDblAmpersand => Sdl2Keycode::KpDblAmpersand,
			Keycode::KpVerticalBar => Sdl2Keycode::KpVerticalBar,
			Keycode::KpDblVerticalBar => Sdl2Keycode::KpDblVerticalBar,
			Keycode::KpColon => Sdl2Keycode::KpColon,
			Keycode::KpHash => Sdl2Keycode::KpHash,
			Keycode::KpSpace => Sdl2Keycode::KpSpace,
			Keycode::KpAt => Sdl2Keycode::KpAt,
			Keycode::KpExclam => Sdl2Keycode::KpExclam,
			Keycode::KpMemStore => Sdl2Keycode::KpMemStore,
			Keycode::KpMemRecall => Sdl2Keycode::KpMemRecall,
			Keycode::KpMemClear => Sdl2Keycode::KpMemClear,
			Keycode::KpMemAdd => Sdl2Keycode::KpMemAdd,
			Keycode::KpMemSubtract => Sdl2Keycode::KpMemSubtract,
			Keycode::KpMemMultiply => Sdl2Keycode::KpMemMultiply,
			Keycode::KpMemDivide => Sdl2Keycode::KpMemDivide,
			Keycode::KpPlusMinus => Sdl2Keycode::KpPlusMinus,
			Keycode::KpClear => Sdl2Keycode::KpClear,
			Keycode::KpClearEntry => Sdl2Keycode::KpClearEntry,
			Keycode::KpBinary => Sdl2Keycode::KpBinary,
			Keycode::KpOctal => Sdl2Keycode::KpOctal,
			Keycode::KpDecimal => Sdl2Keycode::KpDecimal,
			Keycode::KpHexadecimal => Sdl2Keycode::KpHexadecimal,
			Keycode::LCtrl => Sdl2Keycode::LCtrl,
			Keycode::LShift => Sdl2Keycode::LShift,
			Keycode::LAlt => Sdl2Keycode::LAlt,
			Keycode::LGui => Sdl2Keycode::LGui,
			Keycode::RCtrl => Sdl2Keycode::RCtrl,
			Keycode::RShift => Sdl2Keycode::RShift,
			Keycode::RAlt => Sdl2Keycode::RAlt,
			Keycode::RGui => Sdl2Keycode::RGui,
			Keycode::Mode => Sdl2Keycode::Mode,
			Keycode::AudioNext => Sdl2Keycode::AudioNext,
			Keycode::AudioPrev => Sdl2Keycode::AudioPrev,
			Keycode::AudioStop => Sdl2Keycode::AudioStop,
			Keycode::AudioPlay => Sdl2Keycode::AudioPlay,
			Keycode::AudioMute => Sdl2Keycode::AudioMute,
			Keycode::MediaSelect => Sdl2Keycode::MediaSelect,
			Keycode::Www => Sdl2Keycode::Www,
			Keycode::Mail => Sdl2Keycode::Mail,
			Keycode::Calculator => Sdl2Keycode::Calculator,
			Keycode::Computer => Sdl2Keycode::Computer,
			Keycode::AcSearch => Sdl2Keycode::AcSearch,
			Keycode::AcHome => Sdl2Keycode::AcHome,
			Keycode::AcBack => Sdl2Keycode::AcBack,
			Keycode::AcForward => Sdl2Keycode::AcForward,
			Keycode::AcStop => Sdl2Keycode::AcStop,
			Keycode::AcRefresh => Sdl2Keycode::AcRefresh,
			Keycode::AcBookmarks => Sdl2Keycode::AcBookmarks,
			Keycode::BrightnessDown => Sdl2Keycode::BrightnessDown,
			Keycode::BrightnessUp => Sdl2Keycode::BrightnessUp,
			Keycode::DisplaySwitch => Sdl2Keycode::DisplaySwitch,
			Keycode::KbdIllumToggle => Sdl2Keycode::KbdIllumToggle,
			Keycode::KbdIllumDown => Sdl2Keycode::KbdIllumDown,
			Keycode::KbdIllumUp => Sdl2Keycode::KbdIllumUp,
			Keycode::Eject => Sdl2Keycode::Eject,
			Keycode::Sleep => Sdl2Keycode::Sleep,
		}
	}
}

impl Keycode {
	pub fn from_scancode(scancode: Scancode) -> Option<Keycode> {
		Sdl2Keycode::from_scancode(scancode.into()).map(|keycode| keycode.into())
	}

	pub fn name(self) -> String {
		Sdl2Keycode::from(self).name()
	}
}
