[package]
name = "micro-starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
egui = "0.24.0"
glam = "0.24.0"
hecs = "0.10.3"
micro = { path = "../micro", features = ["resource_management"] }
palette = { version = "0.7.2", default-features = false, features = [
	"std",
	"bytemuck",
] }
tracing = "0.1.37"

[build-dependencies]
embed-manifest = "1.3.1"
