[package]
name = "micro-starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21.0"
glam = "0.24.0"
hecs = "0.10.3"
micro = { path = "../micro" }

[build-dependencies]
embed-manifest = "1.3.1"
