use sdl2::keyboard::{Keycode, Scancode as Sdl2Scancode};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "serializing", derive(serde::Serialize, serde::Deserialize))]
pub enum Scancode {
	A,
	B,
	C,
	D,
	E,
	F,
	G,
	H,
	I,
	J,
	K,
	L,
	M,
	N,
	O,
	P,
	Q,
	R,
	S,
	T,
	U,
	V,
	W,
	X,
	Y,
	Z,
	Num1,
	Num2,
	Num3,
	Num4,
	Num5,
	Num6,
	Num7,
	Num8,
	Num9,
	Num0,
	Return,
	Escape,
	Backspace,
	Tab,
	Space,
	Minus,
	Equals,
	LeftBracket,
	RightBracket,
	Backslash,
	NonUsHash,
	Semicolon,
	Apostrophe,
	Grave,
	Comma,
	Period,
	Slash,
	CapsLock,
	F1,
	F2,
	F3,
	F4,
	F5,
	F6,
	F7,
	F8,
	F9,
	F10,
	F11,
	F12,
	PrintScreen,
	ScrollLock,
	Pause,
	Insert,
	Home,
	PageUp,
	Delete,
	End,
	PageDown,
	Right,
	Left,
	Down,
	Up,
	NumLockClear,
	KpDivide,
	KpMultiply,
	KpMinus,
	KpPlus,
	KpEnter,
	Kp1,
	Kp2,
	Kp3,
	Kp4,
	Kp5,
	Kp6,
	Kp7,
	Kp8,
	Kp9,
	Kp0,
	KpPeriod,
	NonUsBackslash,
	Application,
	Power,
	KpEquals,
	F13,
	F14,
	F15,
	F16,
	F17,
	F18,
	F19,
	F20,
	F21,
	F22,
	F23,
	F24,
	Execute,
	Help,
	Menu,
	Select,
	Stop,
	Again,
	Undo,
	Cut,
	Copy,
	Paste,
	Find,
	Mute,
	VolumeUp,
	VolumeDown,
	KpComma,
	KpEqualsAS400,
	International1,
	International2,
	International3,
	International4,
	International5,
	International6,
	International7,
	International8,
	International9,
	Lang1,
	Lang2,
	Lang3,
	Lang4,
	Lang5,
	Lang6,
	Lang7,
	Lang8,
	Lang9,
	AltErase,
	SysReq,
	Cancel,
	Clear,
	Prior,
	Return2,
	Separator,
	Out,
	Oper,
	ClearAgain,
	CrSel,
	ExSel,
	Kp00,
	Kp000,
	ThousandsSeparator,
	DecimalSeparator,
	CurrencyUnit,
	CurrencySubUnit,
	KpLeftParen,
	KpRightParen,
	KpLeftBrace,
	KpRightBrace,
	KpTab,
	KpBackspace,
	KpA,
	KpB,
	KpC,
	KpD,
	KpE,
	KpF,
	KpXor,
	KpPower,
	KpPercent,
	KpLess,
	KpGreater,
	KpAmpersand,
	KpDblAmpersand,
	KpVerticalBar,
	KpDblVerticalBar,
	KpColon,
	KpHash,
	KpSpace,
	KpAt,
	KpExclam,
	KpMemStore,
	KpMemRecall,
	KpMemClear,
	KpMemAdd,
	KpMemSubtract,
	KpMemMultiply,
	KpMemDivide,
	KpPlusMinus,
	KpClear,
	KpClearEntry,
	KpBinary,
	KpOctal,
	KpDecimal,
	KpHexadecimal,
	LCtrl,
	LShift,
	LAlt,
	LGui,
	RCtrl,
	RShift,
	RAlt,
	RGui,
	Mode,
	AudioNext,
	AudioPrev,
	AudioStop,
	AudioPlay,
	AudioMute,
	MediaSelect,
	Www,
	Mail,
	Calculator,
	Computer,
	AcSearch,
	AcHome,
	AcBack,
	AcForward,
	AcStop,
	AcRefresh,
	AcBookmarks,
	BrightnessDown,
	BrightnessUp,
	DisplaySwitch,
	KbdIllumToggle,
	KbdIllumDown,
	KbdIllumUp,
	Eject,
	Sleep,
	App1,
	App2,
	Num,
}

impl From<Sdl2Scancode> for Scancode {
	fn from(value: Sdl2Scancode) -> Self {
		match value {
			Sdl2Scancode::A => Scancode::A,
			Sdl2Scancode::B => Scancode::B,
			Sdl2Scancode::C => Scancode::C,
			Sdl2Scancode::D => Scancode::D,
			Sdl2Scancode::E => Scancode::E,
			Sdl2Scancode::F => Scancode::F,
			Sdl2Scancode::G => Scancode::G,
			Sdl2Scancode::H => Scancode::H,
			Sdl2Scancode::I => Scancode::I,
			Sdl2Scancode::J => Scancode::J,
			Sdl2Scancode::K => Scancode::K,
			Sdl2Scancode::L => Scancode::L,
			Sdl2Scancode::M => Scancode::M,
			Sdl2Scancode::N => Scancode::N,
			Sdl2Scancode::O => Scancode::O,
			Sdl2Scancode::P => Scancode::P,
			Sdl2Scancode::Q => Scancode::Q,
			Sdl2Scancode::R => Scancode::R,
			Sdl2Scancode::S => Scancode::S,
			Sdl2Scancode::T => Scancode::T,
			Sdl2Scancode::U => Scancode::U,
			Sdl2Scancode::V => Scancode::V,
			Sdl2Scancode::W => Scancode::W,
			Sdl2Scancode::X => Scancode::X,
			Sdl2Scancode::Y => Scancode::Y,
			Sdl2Scancode::Z => Scancode::Z,
			Sdl2Scancode::Num1 => Scancode::Num1,
			Sdl2Scancode::Num2 => Scancode::Num2,
			Sdl2Scancode::Num3 => Scancode::Num3,
			Sdl2Scancode::Num4 => Scancode::Num4,
			Sdl2Scancode::Num5 => Scancode::Num5,
			Sdl2Scancode::Num6 => Scancode::Num6,
			Sdl2Scancode::Num7 => Scancode::Num7,
			Sdl2Scancode::Num8 => Scancode::Num8,
			Sdl2Scancode::Num9 => Scancode::Num9,
			Sdl2Scancode::Num0 => Scancode::Num0,
			Sdl2Scancode::Return => Scancode::Return,
			Sdl2Scancode::Escape => Scancode::Escape,
			Sdl2Scancode::Backspace => Scancode::Backspace,
			Sdl2Scancode::Tab => Scancode::Tab,
			Sdl2Scancode::Space => Scancode::Space,
			Sdl2Scancode::Minus => Scancode::Minus,
			Sdl2Scancode::Equals => Scancode::Equals,
			Sdl2Scancode::LeftBracket => Scancode::LeftBracket,
			Sdl2Scancode::RightBracket => Scancode::RightBracket,
			Sdl2Scancode::Backslash => Scancode::Backslash,
			Sdl2Scancode::NonUsHash => Scancode::NonUsHash,
			Sdl2Scancode::Semicolon => Scancode::Semicolon,
			Sdl2Scancode::Apostrophe => Scancode::Apostrophe,
			Sdl2Scancode::Grave => Scancode::Grave,
			Sdl2Scancode::Comma => Scancode::Comma,
			Sdl2Scancode::Period => Scancode::Period,
			Sdl2Scancode::Slash => Scancode::Slash,
			Sdl2Scancode::CapsLock => Scancode::CapsLock,
			Sdl2Scancode::F1 => Scancode::F1,
			Sdl2Scancode::F2 => Scancode::F2,
			Sdl2Scancode::F3 => Scancode::F3,
			Sdl2Scancode::F4 => Scancode::F4,
			Sdl2Scancode::F5 => Scancode::F5,
			Sdl2Scancode::F6 => Scancode::F6,
			Sdl2Scancode::F7 => Scancode::F7,
			Sdl2Scancode::F8 => Scancode::F8,
			Sdl2Scancode::F9 => Scancode::F9,
			Sdl2Scancode::F10 => Scancode::F10,
			Sdl2Scancode::F11 => Scancode::F11,
			Sdl2Scancode::F12 => Scancode::F12,
			Sdl2Scancode::PrintScreen => Scancode::PrintScreen,
			Sdl2Scancode::ScrollLock => Scancode::ScrollLock,
			Sdl2Scancode::Pause => Scancode::Pause,
			Sdl2Scancode::Insert => Scancode::Insert,
			Sdl2Scancode::Home => Scancode::Home,
			Sdl2Scancode::PageUp => Scancode::PageUp,
			Sdl2Scancode::Delete => Scancode::Delete,
			Sdl2Scancode::End => Scancode::End,
			Sdl2Scancode::PageDown => Scancode::PageDown,
			Sdl2Scancode::Right => Scancode::Right,
			Sdl2Scancode::Left => Scancode::Left,
			Sdl2Scancode::Down => Scancode::Down,
			Sdl2Scancode::Up => Scancode::Up,
			Sdl2Scancode::NumLockClear => Scancode::NumLockClear,
			Sdl2Scancode::KpDivide => Scancode::KpDivide,
			Sdl2Scancode::KpMultiply => Scancode::KpMultiply,
			Sdl2Scancode::KpMinus => Scancode::KpMinus,
			Sdl2Scancode::KpPlus => Scancode::KpPlus,
			Sdl2Scancode::KpEnter => Scancode::KpEnter,
			Sdl2Scancode::Kp1 => Scancode::Kp1,
			Sdl2Scancode::Kp2 => Scancode::Kp2,
			Sdl2Scancode::Kp3 => Scancode::Kp3,
			Sdl2Scancode::Kp4 => Scancode::Kp4,
			Sdl2Scancode::Kp5 => Scancode::Kp5,
			Sdl2Scancode::Kp6 => Scancode::Kp6,
			Sdl2Scancode::Kp7 => Scancode::Kp7,
			Sdl2Scancode::Kp8 => Scancode::Kp8,
			Sdl2Scancode::Kp9 => Scancode::Kp9,
			Sdl2Scancode::Kp0 => Scancode::Kp0,
			Sdl2Scancode::KpPeriod => Scancode::KpPeriod,
			Sdl2Scancode::NonUsBackslash => Scancode::NonUsBackslash,
			Sdl2Scancode::Application => Scancode::Application,
			Sdl2Scancode::Power => Scancode::Power,
			Sdl2Scancode::KpEquals => Scancode::KpEquals,
			Sdl2Scancode::F13 => Scancode::F13,
			Sdl2Scancode::F14 => Scancode::F14,
			Sdl2Scancode::F15 => Scancode::F15,
			Sdl2Scancode::F16 => Scancode::F16,
			Sdl2Scancode::F17 => Scancode::F17,
			Sdl2Scancode::F18 => Scancode::F18,
			Sdl2Scancode::F19 => Scancode::F19,
			Sdl2Scancode::F20 => Scancode::F20,
			Sdl2Scancode::F21 => Scancode::F21,
			Sdl2Scancode::F22 => Scancode::F22,
			Sdl2Scancode::F23 => Scancode::F23,
			Sdl2Scancode::F24 => Scancode::F24,
			Sdl2Scancode::Execute => Scancode::Execute,
			Sdl2Scancode::Help => Scancode::Help,
			Sdl2Scancode::Menu => Scancode::Menu,
			Sdl2Scancode::Select => Scancode::Select,
			Sdl2Scancode::Stop => Scancode::Stop,
			Sdl2Scancode::Again => Scancode::Again,
			Sdl2Scancode::Undo => Scancode::Undo,
			Sdl2Scancode::Cut => Scancode::Cut,
			Sdl2Scancode::Copy => Scancode::Copy,
			Sdl2Scancode::Paste => Scancode::Paste,
			Sdl2Scancode::Find => Scancode::Find,
			Sdl2Scancode::Mute => Scancode::Mute,
			Sdl2Scancode::VolumeUp => Scancode::VolumeUp,
			Sdl2Scancode::VolumeDown => Scancode::VolumeDown,
			Sdl2Scancode::KpComma => Scancode::KpComma,
			Sdl2Scancode::KpEqualsAS400 => Scancode::KpEqualsAS400,
			Sdl2Scancode::International1 => Scancode::International1,
			Sdl2Scancode::International2 => Scancode::International2,
			Sdl2Scancode::International3 => Scancode::International3,
			Sdl2Scancode::International4 => Scancode::International4,
			Sdl2Scancode::International5 => Scancode::International5,
			Sdl2Scancode::International6 => Scancode::International6,
			Sdl2Scancode::International7 => Scancode::International7,
			Sdl2Scancode::International8 => Scancode::International8,
			Sdl2Scancode::International9 => Scancode::International9,
			Sdl2Scancode::Lang1 => Scancode::Lang1,
			Sdl2Scancode::Lang2 => Scancode::Lang2,
			Sdl2Scancode::Lang3 => Scancode::Lang3,
			Sdl2Scancode::Lang4 => Scancode::Lang4,
			Sdl2Scancode::Lang5 => Scancode::Lang5,
			Sdl2Scancode::Lang6 => Scancode::Lang6,
			Sdl2Scancode::Lang7 => Scancode::Lang7,
			Sdl2Scancode::Lang8 => Scancode::Lang8,
			Sdl2Scancode::Lang9 => Scancode::Lang9,
			Sdl2Scancode::AltErase => Scancode::AltErase,
			Sdl2Scancode::SysReq => Scancode::SysReq,
			Sdl2Scancode::Cancel => Scancode::Cancel,
			Sdl2Scancode::Clear => Scancode::Clear,
			Sdl2Scancode::Prior => Scancode::Prior,
			Sdl2Scancode::Return2 => Scancode::Return2,
			Sdl2Scancode::Separator => Scancode::Separator,
			Sdl2Scancode::Out => Scancode::Out,
			Sdl2Scancode::Oper => Scancode::Oper,
			Sdl2Scancode::ClearAgain => Scancode::ClearAgain,
			Sdl2Scancode::CrSel => Scancode::CrSel,
			Sdl2Scancode::ExSel => Scancode::ExSel,
			Sdl2Scancode::Kp00 => Scancode::Kp00,
			Sdl2Scancode::Kp000 => Scancode::Kp000,
			Sdl2Scancode::ThousandsSeparator => Scancode::ThousandsSeparator,
			Sdl2Scancode::DecimalSeparator => Scancode::DecimalSeparator,
			Sdl2Scancode::CurrencyUnit => Scancode::CurrencyUnit,
			Sdl2Scancode::CurrencySubUnit => Scancode::CurrencySubUnit,
			Sdl2Scancode::KpLeftParen => Scancode::KpLeftParen,
			Sdl2Scancode::KpRightParen => Scancode::KpRightParen,
			Sdl2Scancode::KpLeftBrace => Scancode::KpLeftBrace,
			Sdl2Scancode::KpRightBrace => Scancode::KpRightBrace,
			Sdl2Scancode::KpTab => Scancode::KpTab,
			Sdl2Scancode::KpBackspace => Scancode::KpBackspace,
			Sdl2Scancode::KpA => Scancode::KpA,
			Sdl2Scancode::KpB => Scancode::KpB,
			Sdl2Scancode::KpC => Scancode::KpC,
			Sdl2Scancode::KpD => Scancode::KpD,
			Sdl2Scancode::KpE => Scancode::KpE,
			Sdl2Scancode::KpF => Scancode::KpF,
			Sdl2Scancode::KpXor => Scancode::KpXor,
			Sdl2Scancode::KpPower => Scancode::KpPower,
			Sdl2Scancode::KpPercent => Scancode::KpPercent,
			Sdl2Scancode::KpLess => Scancode::KpLess,
			Sdl2Scancode::KpGreater => Scancode::KpGreater,
			Sdl2Scancode::KpAmpersand => Scancode::KpAmpersand,
			Sdl2Scancode::KpDblAmpersand => Scancode::KpDblAmpersand,
			Sdl2Scancode::KpVerticalBar => Scancode::KpVerticalBar,
			Sdl2Scancode::KpDblVerticalBar => Scancode::KpDblVerticalBar,
			Sdl2Scancode::KpColon => Scancode::KpColon,
			Sdl2Scancode::KpHash => Scancode::KpHash,
			Sdl2Scancode::KpSpace => Scancode::KpSpace,
			Sdl2Scancode::KpAt => Scancode::KpAt,
			Sdl2Scancode::KpExclam => Scancode::KpExclam,
			Sdl2Scancode::KpMemStore => Scancode::KpMemStore,
			Sdl2Scancode::KpMemRecall => Scancode::KpMemRecall,
			Sdl2Scancode::KpMemClear => Scancode::KpMemClear,
			Sdl2Scancode::KpMemAdd => Scancode::KpMemAdd,
			Sdl2Scancode::KpMemSubtract => Scancode::KpMemSubtract,
			Sdl2Scancode::KpMemMultiply => Scancode::KpMemMultiply,
			Sdl2Scancode::KpMemDivide => Scancode::KpMemDivide,
			Sdl2Scancode::KpPlusMinus => Scancode::KpPlusMinus,
			Sdl2Scancode::KpClear => Scancode::KpClear,
			Sdl2Scancode::KpClearEntry => Scancode::KpClearEntry,
			Sdl2Scancode::KpBinary => Scancode::KpBinary,
			Sdl2Scancode::KpOctal => Scancode::KpOctal,
			Sdl2Scancode::KpDecimal => Scancode::KpDecimal,
			Sdl2Scancode::KpHexadecimal => Scancode::KpHexadecimal,
			Sdl2Scancode::LCtrl => Scancode::LCtrl,
			Sdl2Scancode::LShift => Scancode::LShift,
			Sdl2Scancode::LAlt => Scancode::LAlt,
			Sdl2Scancode::LGui => Scancode::LGui,
			Sdl2Scancode::RCtrl => Scancode::RCtrl,
			Sdl2Scancode::RShift => Scancode::RShift,
			Sdl2Scancode::RAlt => Scancode::RAlt,
			Sdl2Scancode::RGui => Scancode::RGui,
			Sdl2Scancode::Mode => Scancode::Mode,
			Sdl2Scancode::AudioNext => Scancode::AudioNext,
			Sdl2Scancode::AudioPrev => Scancode::AudioPrev,
			Sdl2Scancode::AudioStop => Scancode::AudioStop,
			Sdl2Scancode::AudioPlay => Scancode::AudioPlay,
			Sdl2Scancode::AudioMute => Scancode::AudioMute,
			Sdl2Scancode::MediaSelect => Scancode::MediaSelect,
			Sdl2Scancode::Www => Scancode::Www,
			Sdl2Scancode::Mail => Scancode::Mail,
			Sdl2Scancode::Calculator => Scancode::Calculator,
			Sdl2Scancode::Computer => Scancode::Computer,
			Sdl2Scancode::AcSearch => Scancode::AcSearch,
			Sdl2Scancode::AcHome => Scancode::AcHome,
			Sdl2Scancode::AcBack => Scancode::AcBack,
			Sdl2Scancode::AcForward => Scancode::AcForward,
			Sdl2Scancode::AcStop => Scancode::AcStop,
			Sdl2Scancode::AcRefresh => Scancode::AcRefresh,
			Sdl2Scancode::AcBookmarks => Scancode::AcBookmarks,
			Sdl2Scancode::BrightnessDown => Scancode::BrightnessDown,
			Sdl2Scancode::BrightnessUp => Scancode::BrightnessUp,
			Sdl2Scancode::DisplaySwitch => Scancode::DisplaySwitch,
			Sdl2Scancode::KbdIllumToggle => Scancode::KbdIllumToggle,
			Sdl2Scancode::KbdIllumDown => Scancode::KbdIllumDown,
			Sdl2Scancode::KbdIllumUp => Scancode::KbdIllumUp,
			Sdl2Scancode::Eject => Scancode::Eject,
			Sdl2Scancode::Sleep => Scancode::Sleep,
			Sdl2Scancode::App1 => Scancode::App1,
			Sdl2Scancode::App2 => Scancode::App2,
			Sdl2Scancode::Num => Scancode::Num,
		}
	}
}

impl From<Scancode> for Sdl2Scancode {
	fn from(value: Scancode) -> Self {
		match value {
			Scancode::A => Sdl2Scancode::A,
			Scancode::B => Sdl2Scancode::B,
			Scancode::C => Sdl2Scancode::C,
			Scancode::D => Sdl2Scancode::D,
			Scancode::E => Sdl2Scancode::E,
			Scancode::F => Sdl2Scancode::F,
			Scancode::G => Sdl2Scancode::G,
			Scancode::H => Sdl2Scancode::H,
			Scancode::I => Sdl2Scancode::I,
			Scancode::J => Sdl2Scancode::J,
			Scancode::K => Sdl2Scancode::K,
			Scancode::L => Sdl2Scancode::L,
			Scancode::M => Sdl2Scancode::M,
			Scancode::N => Sdl2Scancode::N,
			Scancode::O => Sdl2Scancode::O,
			Scancode::P => Sdl2Scancode::P,
			Scancode::Q => Sdl2Scancode::Q,
			Scancode::R => Sdl2Scancode::R,
			Scancode::S => Sdl2Scancode::S,
			Scancode::T => Sdl2Scancode::T,
			Scancode::U => Sdl2Scancode::U,
			Scancode::V => Sdl2Scancode::V,
			Scancode::W => Sdl2Scancode::W,
			Scancode::X => Sdl2Scancode::X,
			Scancode::Y => Sdl2Scancode::Y,
			Scancode::Z => Sdl2Scancode::Z,
			Scancode::Num1 => Sdl2Scancode::Num1,
			Scancode::Num2 => Sdl2Scancode::Num2,
			Scancode::Num3 => Sdl2Scancode::Num3,
			Scancode::Num4 => Sdl2Scancode::Num4,
			Scancode::Num5 => Sdl2Scancode::Num5,
			Scancode::Num6 => Sdl2Scancode::Num6,
			Scancode::Num7 => Sdl2Scancode::Num7,
			Scancode::Num8 => Sdl2Scancode::Num8,
			Scancode::Num9 => Sdl2Scancode::Num9,
			Scancode::Num0 => Sdl2Scancode::Num0,
			Scancode::Return => Sdl2Scancode::Return,
			Scancode::Escape => Sdl2Scancode::Escape,
			Scancode::Backspace => Sdl2Scancode::Backspace,
			Scancode::Tab => Sdl2Scancode::Tab,
			Scancode::Space => Sdl2Scancode::Space,
			Scancode::Minus => Sdl2Scancode::Minus,
			Scancode::Equals => Sdl2Scancode::Equals,
			Scancode::LeftBracket => Sdl2Scancode::LeftBracket,
			Scancode::RightBracket => Sdl2Scancode::RightBracket,
			Scancode::Backslash => Sdl2Scancode::Backslash,
			Scancode::NonUsHash => Sdl2Scancode::NonUsHash,
			Scancode::Semicolon => Sdl2Scancode::Semicolon,
			Scancode::Apostrophe => Sdl2Scancode::Apostrophe,
			Scancode::Grave => Sdl2Scancode::Grave,
			Scancode::Comma => Sdl2Scancode::Comma,
			Scancode::Period => Sdl2Scancode::Period,
			Scancode::Slash => Sdl2Scancode::Slash,
			Scancode::CapsLock => Sdl2Scancode::CapsLock,
			Scancode::F1 => Sdl2Scancode::F1,
			Scancode::F2 => Sdl2Scancode::F2,
			Scancode::F3 => Sdl2Scancode::F3,
			Scancode::F4 => Sdl2Scancode::F4,
			Scancode::F5 => Sdl2Scancode::F5,
			Scancode::F6 => Sdl2Scancode::F6,
			Scancode::F7 => Sdl2Scancode::F7,
			Scancode::F8 => Sdl2Scancode::F8,
			Scancode::F9 => Sdl2Scancode::F9,
			Scancode::F10 => Sdl2Scancode::F10,
			Scancode::F11 => Sdl2Scancode::F11,
			Scancode::F12 => Sdl2Scancode::F12,
			Scancode::PrintScreen => Sdl2Scancode::PrintScreen,
			Scancode::ScrollLock => Sdl2Scancode::ScrollLock,
			Scancode::Pause => Sdl2Scancode::Pause,
			Scancode::Insert => Sdl2Scancode::Insert,
			Scancode::Home => Sdl2Scancode::Home,
			Scancode::PageUp => Sdl2Scancode::PageUp,
			Scancode::Delete => Sdl2Scancode::Delete,
			Scancode::End => Sdl2Scancode::End,
			Scancode::PageDown => Sdl2Scancode::PageDown,
			Scancode::Right => Sdl2Scancode::Right,
			Scancode::Left => Sdl2Scancode::Left,
			Scancode::Down => Sdl2Scancode::Down,
			Scancode::Up => Sdl2Scancode::Up,
			Scancode::NumLockClear => Sdl2Scancode::NumLockClear,
			Scancode::KpDivide => Sdl2Scancode::KpDivide,
			Scancode::KpMultiply => Sdl2Scancode::KpMultiply,
			Scancode::KpMinus => Sdl2Scancode::KpMinus,
			Scancode::KpPlus => Sdl2Scancode::KpPlus,
			Scancode::KpEnter => Sdl2Scancode::KpEnter,
			Scancode::Kp1 => Sdl2Scancode::Kp1,
			Scancode::Kp2 => Sdl2Scancode::Kp2,
			Scancode::Kp3 => Sdl2Scancode::Kp3,
			Scancode::Kp4 => Sdl2Scancode::Kp4,
			Scancode::Kp5 => Sdl2Scancode::Kp5,
			Scancode::Kp6 => Sdl2Scancode::Kp6,
			Scancode::Kp7 => Sdl2Scancode::Kp7,
			Scancode::Kp8 => Sdl2Scancode::Kp8,
			Scancode::Kp9 => Sdl2Scancode::Kp9,
			Scancode::Kp0 => Sdl2Scancode::Kp0,
			Scancode::KpPeriod => Sdl2Scancode::KpPeriod,
			Scancode::NonUsBackslash => Sdl2Scancode::NonUsBackslash,
			Scancode::Application => Sdl2Scancode::Application,
			Scancode::Power => Sdl2Scancode::Power,
			Scancode::KpEquals => Sdl2Scancode::KpEquals,
			Scancode::F13 => Sdl2Scancode::F13,
			Scancode::F14 => Sdl2Scancode::F14,
			Scancode::F15 => Sdl2Scancode::F15,
			Scancode::F16 => Sdl2Scancode::F16,
			Scancode::F17 => Sdl2Scancode::F17,
			Scancode::F18 => Sdl2Scancode::F18,
			Scancode::F19 => Sdl2Scancode::F19,
			Scancode::F20 => Sdl2Scancode::F20,
			Scancode::F21 => Sdl2Scancode::F21,
			Scancode::F22 => Sdl2Scancode::F22,
			Scancode::F23 => Sdl2Scancode::F23,
			Scancode::F24 => Sdl2Scancode::F24,
			Scancode::Execute => Sdl2Scancode::Execute,
			Scancode::Help => Sdl2Scancode::Help,
			Scancode::Menu => Sdl2Scancode::Menu,
			Scancode::Select => Sdl2Scancode::Select,
			Scancode::Stop => Sdl2Scancode::Stop,
			Scancode::Again => Sdl2Scancode::Again,
			Scancode::Undo => Sdl2Scancode::Undo,
			Scancode::Cut => Sdl2Scancode::Cut,
			Scancode::Copy => Sdl2Scancode::Copy,
			Scancode::Paste => Sdl2Scancode::Paste,
			Scancode::Find => Sdl2Scancode::Find,
			Scancode::Mute => Sdl2Scancode::Mute,
			Scancode::VolumeUp => Sdl2Scancode::VolumeUp,
			Scancode::VolumeDown => Sdl2Scancode::VolumeDown,
			Scancode::KpComma => Sdl2Scancode::KpComma,
			Scancode::KpEqualsAS400 => Sdl2Scancode::KpEqualsAS400,
			Scancode::International1 => Sdl2Scancode::International1,
			Scancode::International2 => Sdl2Scancode::International2,
			Scancode::International3 => Sdl2Scancode::International3,
			Scancode::International4 => Sdl2Scancode::International4,
			Scancode::International5 => Sdl2Scancode::International5,
			Scancode::International6 => Sdl2Scancode::International6,
			Scancode::International7 => Sdl2Scancode::International7,
			Scancode::International8 => Sdl2Scancode::International8,
			Scancode::International9 => Sdl2Scancode::International9,
			Scancode::Lang1 => Sdl2Scancode::Lang1,
			Scancode::Lang2 => Sdl2Scancode::Lang2,
			Scancode::Lang3 => Sdl2Scancode::Lang3,
			Scancode::Lang4 => Sdl2Scancode::Lang4,
			Scancode::Lang5 => Sdl2Scancode::Lang5,
			Scancode::Lang6 => Sdl2Scancode::Lang6,
			Scancode::Lang7 => Sdl2Scancode::Lang7,
			Scancode::Lang8 => Sdl2Scancode::Lang8,
			Scancode::Lang9 => Sdl2Scancode::Lang9,
			Scancode::AltErase => Sdl2Scancode::AltErase,
			Scancode::SysReq => Sdl2Scancode::SysReq,
			Scancode::Cancel => Sdl2Scancode::Cancel,
			Scancode::Clear => Sdl2Scancode::Clear,
			Scancode::Prior => Sdl2Scancode::Prior,
			Scancode::Return2 => Sdl2Scancode::Return2,
			Scancode::Separator => Sdl2Scancode::Separator,
			Scancode::Out => Sdl2Scancode::Out,
			Scancode::Oper => Sdl2Scancode::Oper,
			Scancode::ClearAgain => Sdl2Scancode::ClearAgain,
			Scancode::CrSel => Sdl2Scancode::CrSel,
			Scancode::ExSel => Sdl2Scancode::ExSel,
			Scancode::Kp00 => Sdl2Scancode::Kp00,
			Scancode::Kp000 => Sdl2Scancode::Kp000,
			Scancode::ThousandsSeparator => Sdl2Scancode::ThousandsSeparator,
			Scancode::DecimalSeparator => Sdl2Scancode::DecimalSeparator,
			Scancode::CurrencyUnit => Sdl2Scancode::CurrencyUnit,
			Scancode::CurrencySubUnit => Sdl2Scancode::CurrencySubUnit,
			Scancode::KpLeftParen => Sdl2Scancode::KpLeftParen,
			Scancode::KpRightParen => Sdl2Scancode::KpRightParen,
			Scancode::KpLeftBrace => Sdl2Scancode::KpLeftBrace,
			Scancode::KpRightBrace => Sdl2Scancode::KpRightBrace,
			Scancode::KpTab => Sdl2Scancode::KpTab,
			Scancode::KpBackspace => Sdl2Scancode::KpBackspace,
			Scancode::KpA => Sdl2Scancode::KpA,
			Scancode::KpB => Sdl2Scancode::KpB,
			Scancode::KpC => Sdl2Scancode::KpC,
			Scancode::KpD => Sdl2Scancode::KpD,
			Scancode::KpE => Sdl2Scancode::KpE,
			Scancode::KpF => Sdl2Scancode::KpF,
			Scancode::KpXor => Sdl2Scancode::KpXor,
			Scancode::KpPower => Sdl2Scancode::KpPower,
			Scancode::KpPercent => Sdl2Scancode::KpPercent,
			Scancode::KpLess => Sdl2Scancode::KpLess,
			Scancode::KpGreater => Sdl2Scancode::KpGreater,
			Scancode::KpAmpersand => Sdl2Scancode::KpAmpersand,
			Scancode::KpDblAmpersand => Sdl2Scancode::KpDblAmpersand,
			Scancode::KpVerticalBar => Sdl2Scancode::KpVerticalBar,
			Scancode::KpDblVerticalBar => Sdl2Scancode::KpDblVerticalBar,
			Scancode::KpColon => Sdl2Scancode::KpColon,
			Scancode::KpHash => Sdl2Scancode::KpHash,
			Scancode::KpSpace => Sdl2Scancode::KpSpace,
			Scancode::KpAt => Sdl2Scancode::KpAt,
			Scancode::KpExclam => Sdl2Scancode::KpExclam,
			Scancode::KpMemStore => Sdl2Scancode::KpMemStore,
			Scancode::KpMemRecall => Sdl2Scancode::KpMemRecall,
			Scancode::KpMemClear => Sdl2Scancode::KpMemClear,
			Scancode::KpMemAdd => Sdl2Scancode::KpMemAdd,
			Scancode::KpMemSubtract => Sdl2Scancode::KpMemSubtract,
			Scancode::KpMemMultiply => Sdl2Scancode::KpMemMultiply,
			Scancode::KpMemDivide => Sdl2Scancode::KpMemDivide,
			Scancode::KpPlusMinus => Sdl2Scancode::KpPlusMinus,
			Scancode::KpClear => Sdl2Scancode::KpClear,
			Scancode::KpClearEntry => Sdl2Scancode::KpClearEntry,
			Scancode::KpBinary => Sdl2Scancode::KpBinary,
			Scancode::KpOctal => Sdl2Scancode::KpOctal,
			Scancode::KpDecimal => Sdl2Scancode::KpDecimal,
			Scancode::KpHexadecimal => Sdl2Scancode::KpHexadecimal,
			Scancode::LCtrl => Sdl2Scancode::LCtrl,
			Scancode::LShift => Sdl2Scancode::LShift,
			Scancode::LAlt => Sdl2Scancode::LAlt,
			Scancode::LGui => Sdl2Scancode::LGui,
			Scancode::RCtrl => Sdl2Scancode::RCtrl,
			Scancode::RShift => Sdl2Scancode::RShift,
			Scancode::RAlt => Sdl2Scancode::RAlt,
			Scancode::RGui => Sdl2Scancode::RGui,
			Scancode::Mode => Sdl2Scancode::Mode,
			Scancode::AudioNext => Sdl2Scancode::AudioNext,
			Scancode::AudioPrev => Sdl2Scancode::AudioPrev,
			Scancode::AudioStop => Sdl2Scancode::AudioStop,
			Scancode::AudioPlay => Sdl2Scancode::AudioPlay,
			Scancode::AudioMute => Sdl2Scancode::AudioMute,
			Scancode::MediaSelect => Sdl2Scancode::MediaSelect,
			Scancode::Www => Sdl2Scancode::Www,
			Scancode::Mail => Sdl2Scancode::Mail,
			Scancode::Calculator => Sdl2Scancode::Calculator,
			Scancode::Computer => Sdl2Scancode::Computer,
			Scancode::AcSearch => Sdl2Scancode::AcSearch,
			Scancode::AcHome => Sdl2Scancode::AcHome,
			Scancode::AcBack => Sdl2Scancode::AcBack,
			Scancode::AcForward => Sdl2Scancode::AcForward,
			Scancode::AcStop => Sdl2Scancode::AcStop,
			Scancode::AcRefresh => Sdl2Scancode::AcRefresh,
			Scancode::AcBookmarks => Sdl2Scancode::AcBookmarks,
			Scancode::BrightnessDown => Sdl2Scancode::BrightnessDown,
			Scancode::BrightnessUp => Sdl2Scancode::BrightnessUp,
			Scancode::DisplaySwitch => Sdl2Scancode::DisplaySwitch,
			Scancode::KbdIllumToggle => Sdl2Scancode::KbdIllumToggle,
			Scancode::KbdIllumDown => Sdl2Scancode::KbdIllumDown,
			Scancode::KbdIllumUp => Sdl2Scancode::KbdIllumUp,
			Scancode::Eject => Sdl2Scancode::Eject,
			Scancode::Sleep => Sdl2Scancode::Sleep,
			Scancode::App1 => Sdl2Scancode::App1,
			Scancode::App2 => Sdl2Scancode::App2,
			Scancode::Num => Sdl2Scancode::Num,
		}
	}
}

impl Scancode {
	pub fn from_keycode(keycode: Keycode) -> Option<Scancode> {
		Sdl2Scancode::from_keycode(keycode).map(|keycode| keycode.into())
	}

	pub fn name(self) -> &'static str {
		Sdl2Scancode::from(self).name()
	}
}
